DROP DATABASE IF EXISTS TRABALHOAPBD;
CREATE DATABASE TRABALHOAPBD;
USE TRABALHOAPBD;


DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS CARRO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS LOCACAO;
DROP TABLE IF EXISTS ADD_ITENS;
DROP TABLE IF EXISTS LOCALIZACAO;
DROP TABLE IF EXISTS DEVOLUCAO;


CREATE TABLE FUNCIONARIO(
	
    Id INTEGER auto_increment,
    NOME VARCHAR (40),
    CPF CHAR (11),
    
    PRIMARY KEY (Id)

);

CREATE TABLE CARRO(
	
    Placa CHAR(8),
    Modelo CHAR(20),
    Marca CHAR(30),
	Cor CHAR(10),
    Ano	CHAR(4),
    Km INTEGER,
    StatusLoc CHAR(1),
    
    PRIMARY KEY (Placa)

);

CREATE TABLE CLIENTE(
	
    CPF CHAR(11),
    NOME VARCHAR (40),
	TELEFONE CHAR(11),
    ESTADO CHAR(2),
    CIDADE CHAR(20),
    QUANT_RESERVA INTEGER,
    
    PRIMARY KEY (CPF)
);

CREATE TABLE ITENS_ADICIONAIS(
	
    ID INTEGER,
    NOME CHAR(30),
    TIPO CHAR(10),
    VALOR DECIMAL(10,2),
    
    PRIMARY KEY (ID)
);

CREATE TABLE LOCALIZACAO(
	
    CODIGO INTEGER,
    CIDADE CHAR(30),
    
    PRIMARY KEY (CODIGO)
);

CREATE TABLE LOCACAO(
	
    Id INTEGER,
    CPF_CLIENTE CHAR(11),
    Id_funcionario INTEGER,
    Placa_Carro CHAR(8),
    DATA_ALUGUEL DATE,
    DATA_LIMITE DATE,
    ADICIONAIS CHAR(1),
    
    PRIMARY KEY (Id),
    FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF),
    FOREIGN KEY (Id_funcionario) REFERENCES FUNCIONARIO(Id),
    FOREIGN KEY (Placa_Carro) REFERENCES CARRO(Placa)
    
);

CREATE TABLE LOCACAO_POSSUI_ADICIONAIS(
	
    Id INTEGER,
    ID_ADICIONAIS INTEGER,
    
    PRIMARY KEY (Id,ID_ADICIONAIS),
    FOREIGN KEY (Id) REFERENCES LOCACAO(Id),
    FOREIGN KEY (ID_ADICIONAIS) REFERENCES ITENS_ADICIONAIS(ID)
    
);
