DROP DATABASE IF EXISTS TRABALHOAPBD;
CREATE DATABASE TRABALHOAPBD;
USE TRABALHOAPBD;

DROP TABLE IF EXISTS FILIAL;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS CARRO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS LOCACAO;
DROP TABLE IF EXISTS ADD_ITENS;
DROP TABLE IF EXISTS LOCALIZACAO;
DROP TABLE IF EXISTS DEVOLUCAO;


CREATE TABLE FILIAL(
	
    IdFilial CHAR(10),
    LOCALIZACAO CHAR(30),
    
    PRIMARY KEY (IdFilial) 
    
);

CREATE TABLE FUNCIONARIO(
	
    CPF CHAR(11),
    NOME VARCHAR (40),
    IdFilial CHAR(10),
    
    PRIMARY KEY (CPF) ,
    FOREIGN KEY (IdFilial) REFERENCES FILIAL(IdFilial) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CARRO(
	
    PLACA CHAR(8),
    NOME CHAR(20),
    MARCA CHAR(30),
    MODELO CHAR(20),
	KM CHAR(10),
    COR CHAR(10),
    ANO	CHAR(4),
    IDFILIAL CHAR(10),
    STATUSLOC CHAR(1),
    VALOR FLOAT,
    
    PRIMARY KEY (PLACA),
    FOREIGN KEY(IDFILIAL) REFERENCES FILIAL (IdFilial) ON UPDATE CASCADE ON DELETE CASCADE

);

CREATE TABLE CLIENTE(
	
    CPF CHAR(11),
    NOME VARCHAR (40),
	TELEFONE CHAR(13),
    ESTADO CHAR(2),
    CIDADE CHAR(20),
    QUANT_VOUCHER INTEGER,
    
    PRIMARY KEY (CPF)
);

CREATE TABLE ITENS(
	
    ID INTEGER auto_increment,
    NOME CHAR(30),
    VALOR FLOAT,
    
    PRIMARY KEY (ID)
);

CREATE TABLE RESERVA(
	
    Id_reserva INTEGER auto_increment,
    CPF_func CHAR(11),
    CPF_cliente CHAR(11),
    Placa_Carro CHAR(8),
    Id_filial CHAR(10),
    Data_reserva CHAR(10),
    
    PRIMARY KEY (Id_reserva),
    FOREIGN KEY (CPF_func) REFERENCES FUNCIONARIO(CPF) ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY (CPF_cliente) REFERENCES CLIENTE(CPF) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Placa_Carro) REFERENCES CARRO(PLACA) ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY (Id_filial) REFERENCES FILIAL(IdFilial) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE LOCACAO(
	
    Id INTEGER auto_increment,
    Id_reserva integer,
    CPF_CLIENTE CHAR(11),
    CPF_funcionario CHAR(11),
    Placa_Carro CHAR(8),
    Id_filial CHAR(10),
    DATA_ALUGUEL CHAR(10),
    DATA_DEVOLUCAO CHAR(10),
    VALOR FLOAT,
    
    PRIMARY KEY (Id),
    FOREIGN KEY (Id_reserva) REFERENCES RESERVA(Id_reserva) ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF) ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY (CPF_funcionario) REFERENCES FUNCIONARIO(CPF) ON DELETE NO ACTION ON UPDATE CASCADE,
    FOREIGN KEY (Placa_Carro) REFERENCES CARRO(PLACA) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY (Id_filial) REFERENCES FILIAL(IdFilial) ON DELETE CASCADE ON UPDATE CASCADE
    
    
    
);
/*
CREATE TABLE LOCACAO_POSSUI_ITENS(
	
    Id INTEGER,
    ID_ADICIONAIS INTEGER,
    
    PRIMARY KEY (Id),
    FOREIGN KEY (Id) REFERENCES LOCACAO(Id),
    FOREIGN KEY (ID_ADICIONAIS) REFERENCES ITENS_ADICIONAIS(ID)
    
);
*/

insert into FILIAL values ('001', 'Campo Mourão'),('002', 'Apucarana'),('003', 'Maringá'),('004', 'Londrina');

insert into FUNCIONARIO values ('09685447977', 'Guilherme Canesin','001'),('44031369824', 'Keith Ishibashi','002'),('48512026871', 'Massao Ueda','003'),('16439648799', 'Isabela Gantzel','004');

insert into CLIENTE values ('08134567349', 'André Luis Schwerz', '(44)9934-5548', 'PR','Campo Mourão', 0);

insert into CARRO values ('BBM-4810', 'KICKS','NISSAN','SUV','12530','BRANCO','2016','002','R', '130'),('HRI-3513', 'PRISMA','CHEVROLET','SEDAN','20500','PRATA','2011','001','N','80');

insert into RESERVA (CPF_func,CPF_cliente, Placa_Carro, Id_filial, Data_reserva) values ('09685447977', '08134567349','BBM-4810','001','28/11/2018');

-- insert into LOCACAO (CPF_func,CPF_cliente, Placa_Carro, Id_filial, Data_reserva) values ('09685447977', '08134567349','BBM-4810','001','28/11/2018');

INSERT INTO LOCACAO (Id_reserva,CPF_CLIENTE,CPF_funcionario,Placa_Carro,Id_filial,DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR) 
				VALUES (1,'08134567349','09685447977','BBM-4810','001','27','32','170');

